CREATE TABLE ContatosClientes
(
	Id			INT IDENTITY(1,1) NOT NULL,
	Nome		VARCHAR(300) NOT NULL,
	Rg			VARCHAR(14) SPARSE NULL,
	Cpf			VARCHAR(14) SPARSE NULL,
	EstadoCivil VARCHAR(50) SPARSE NULL,
	Nacionalidade VARCHAR(50) SPARSE NULL,
	Cargo		VARCHAR(100) NOT NULL,
	Email		VARCHAR(300) NOT NULL,
	ClienteId	INT NOT NULL,
	Responsavel BIT NOT NULL DEFAULT(0),
	CONSTRAINT PK_CONTATOSCLIENTES PRIMARY KEY (Id),
	CONSTRAINT FK_CONTATOSCLIENTES_CLIENTE FOREIGN KEY (ClienteId) REFERENCES Clientes(Id),
	CONSTRAINT U_CONTATOSCLIENTES_EMAIL UNIQUE(Email)
)
