CREATE TABLE Clausulas
(
	Id		INT IDENTITY(1,1) NOT NULL,
	Titulo	VARCHAR(300) NOT NULL,
	Termos	NVARCHAR(1000) NOT NULL,
	Ordem	INT NOT NULL DEFAULT (0),
	ContratoId	INT NOT NULL,
	CONSTRAINT PK_CLAUSULA PRIMARY KEY NONCLUSTERED (Id),
	CONSTRAINT FK_CLAUSULA_CONTRATO FOREIGN KEY (ContratoId) REFERENCES Contratos(Id)
)
