CREATE TABLE Fabrica
(
	Id				INT IDENTITY(1,1) NOT NULL,
	NomeFantasia	VARCHAR(300) NOT NULL,
	RazaoSocial		VARCHAR(300) NOT NULL,
	Cnpj			VARCHAR(14) NOT NULL,
	Ie				VARCHAR(14) SPARSE NULL,
	Email			VARCHAR(300) NOT NULL,
	WebSite			VARCHAR(300) NOT NULL,
	CONSTRAINT PK_FABRICA PRIMARY KEY (Id)
)
