CREATE TABLE Clientes
(
	Id				INT IDENTITY(1,1) NOT NULL,
	NomeFantasia	VARCHAR(300) NOT NULL,
	RazaoSocial		VARCHAR(300) NOT NULL,
	Cnpj			VARCHAR(14) NOT NULL,
	Ie				VARCHAR(14) SPARSE NULL,
	Email			VARCHAR(300) NOT NULL,
	WebSite			VARCHAR(300) SPARSE NULL,
	SituacaoId		INT NOT NULL DEFAULT (1),
	CONSTRAINT PK_CLIENTE PRIMARY KEY (Id),
	CONSTRAINT FK_CLIENTE_SITUACAO FOREIGN KEY (SituacaoId) REFERENCES Situacao(Id)
)
