CREATE TABLE Bancos
(
	Id			INT IDENTITY(1,1) NOT NULL,
	Nome		VARCHAR(100) NOT NULL,
	CodigoBC	VARCHAR(3) NOT NULL,
	Ativo		BIT NOT NULL DEFAULT(0),
	CONSTRAINT PK_BANCOS PRIMARY KEY NONCLUSTERED (Id),
	CONSTRAINT UK_BANCOS_CODIGOBC UNIQUE (CodigoBC)
)
