CREATE TABLE EstornosLancamentosContasBancarias
(
	Id INT IDENTITY(1,1) NOT NULL,
	LancamentoId INT NOT NULL,
	TipoLancamentoId INT NOT NULL,
	DataRegistro DATETIME NOT NULL DEFAULT(GETDATE()),
	Valor MONEY NOT NULL,
	CONSTRAINT PK_ESTORNOSLANCAMENTOSCONTASBANCARIAS PRIMARY KEY NONCLUSTERED (Id),
	CONSTRAINT FK_ESTORNOSLANCAMENTOSCONTASBANCARIAS_LANCAMENTO FOREIGN KEY (LancamentoId) REFERENCES LancamentosContasBancarias(Id),
	CONSTRAINT FK_ESTORNOSLANCAMENTOSCONTASBANCARIAS_TIPOLANCAMENTO FOREIGN KEY (TipoLancamentoId) REFERENCES TiposLancamentos(Id)
)
