CREATE TABLE LancamentosContasBancarias
(
	Id					INT IDENTITY(1,1) NOT NULL,
	ContaId				INT NOT NULL,
	TipoLancamentoId	INT NOT NULL,
	DataLancamento		DATETIME NOT NULL DEFAULT(GETDATE()),
	Valor				MONEY NOT NULL,
	Historico			VARCHAR(1000) NOT NULL,
	Estornado			BIT NOT NULL DEFAULT(0),
	CONSTRAINT PK_LANCAMENTOSCONTASBANCARIAS PRIMARY KEY NONCLUSTERED(Id),
	CONSTRAINT FK_LANCAMENTOSCONTASBANCARIAS_CONTABANCARIA FOREIGN KEY (ContaId) REFERENCES ContasBancarias(Id),
	CONSTRAINT FK_LANCAMENTOSCONTASBANCARIAS_TIPOLANCAMENTO FOREIGN KEY (TipoLancamentoId) REFERENCES TiposLancamentos(Id)
)
