CREATE TABLE ContasLiquidadasCaixas
(
	Id INT IDENTITY(1,1) NOT NULL,
	ContaLiquidadaId INT NOT NULL,
	LancamentoCaixaId INT NOT NULL,
	CONSTRAINT PK_CONTASLIQUIDADASCAIXAS PRIMARY KEY NONCLUSTERED(Id),
	CONSTRAINT FK_CONTASLIQUIDADASCAIXAS_CONTA FOREIGN KEY (ContaLiquidadaId) REFERENCES ContasLiquidadas(Id),
	CONSTRAINT FK_CONTASLIQUIDADASCAIXAS_LANCAMENTOCAIXA FOREIGN KEY (LancamentoCaixaId) REFERENCES LancamentosCaixa(Id)
)
