CREATE TABLE ContasLiquidadasBancos
(
	Id INT IDENTITY(1,1) NOT NULL,
	ContaLiquidadaId INT NOT NULL,
	LancamentoContaBancariaId INT NOT NULL,
	CONSTRAINT PK_CONTASLIQUIDADASBANCOS PRIMARY KEY NONCLUSTERED(Id),
	CONSTRAINT FK_CONTASLIQUIDADASBANCOS_CONTALIQUIDADA FOREIGN KEY (ContaLiquidadaId) REFERENCES ContasLiquidadas(Id),
	CONSTRAINT FK_CONTASLIQUIDADASBANCOS_LANCAMENTOCONTABANCARIA FOREIGN KEY (LancamentoContaBancariaId) REFERENCES LancamentosContasBancarias(Id)
)
