CREATE TABLE EstornosTitulosRecebidos
(
	Id INT IDENTITY(1,1) NOT NULL,
	TituloRecebidoId INT NOT NULL,
	DataRegistro DATETIME NOT NULL DEFAULT(GETDATE()),
	Valor MONEY NOT NULL,
	CONSTRAINT PK_ESTORNOSTITULOSRECEBIDOS PRIMARY KEY NONCLUSTERED(Id),
	CONSTRAINT FK_ESTORNOSTITULOSRECEBIDOS_TITULORECEBIDO FOREIGN KEY (TituloRecebidoId) REFERENCES TitulosRecebidos(Id)
)
