CREATE TABLE TitulosRecebiveis
(
	Id INT IDENTITY(1,1) NOT NULL,
	ClienteId INT NOT NULL,
	ContratoId	INT NOT NULL,
	CodigoJurosMoraId INT NOT NULL, --DOMINIO (C018)
	CodigoProtestoId INT NOT NULL, --DOMÍNIO (C026)
	CodigoBaixaId INT NOT NULL, --DOMÍNIO (C028)
	Parcela INT NOT NULL,
	TotalParcelas INT NOT NULL,
	ValorParcela MONEY NOT NULL,
	DataRegistro DATETIME NOT NULL DEFAULT(GETDATE()),
	DataVencimento	DATETIME NOT NULL,
	DataJurosMora DATETIME NOT NULL, --DATAVENCIMENTO +1
	TaxaJurosMora FLOAT NOT NULL,
	DiasParaProtesto INT NOT NULL,
	DiasParaBaixa INT NOT NULL,
	Quitado BIT NOT NULL DEFAULT(0),
	BoletoBancario BIT NOT NULL DEFAULT(0),	 --INDICA QUE FOI GERADO NO BOLETO E ENVIADO PARA O BANCO
	CONSTRAINT PK_TITULOSRECEBIVEIS PRIMARY KEY NONCLUSTERED (Id),
	CONSTRAINT FK_TITULOSRECEBIVEIS_CLIENTE FOREIGN KEY (ClienteId) REFERENCES Clientes(Id),
	CONSTRAINT FK_TITULOSRECEBIVEIS_CONTRATO FOREIGN KEY (ContratoId) REFERENCES Contratos(Id),
	CONSTRAINT FK_TITULOSRECEBIVEIS_CODIGOJUROSMORA FOREIGN KEY (CodigoJurosMoraId) REFERENCES C018_CodigoJurosMora(Id),
	CONSTRAINT FK_TITULOSRECEBIVEIS_CODIGOPROTESTO FOREIGN KEY (CodigoProtestoId) REFERENCES C026_CodigoProtesto(Id),
	CONSTRAINT FK_TITULOSRECEBIVEIS_CODIGOBAIXA FOREIGN KEY (CodigoBaixaId) REFERENCES C028_CodigoBaixaDevolucao (Id)
)
