CREATE TABLE TitulosRecebidos
(
	Id INT IDENTITY(1,1) NOT NULL,
	TituloRecebivelId INT NOT NULL,
	TipoRecebimentoId INT NOT NULL,
	ValorTitulo MONEY NOT NULL,
	ValorRecebido MONEY NOT NULL,
	DataRecebimento DATETIME NOT NULL DEFAULT(GETDATE()),
	CONSTRAINT PK_TITULOSRECEBIDOS PRIMARY KEY NONCLUSTERED(Id),
	CONSTRAINT FK_TITULOSRECEBIDOS_TITULORECEBIVEL FOREIGN KEY (TituloRecebivelId) REFERENCES TitulosRecebiveis(Id),
	CONSTRAINT FK_TITULOSRECEBIDOS_TIPORECEBIMENTO FOREIGN KEY (TipoRecebimentoId) REFERENCES TipoRecebimentoTitulo(Id)

)
