CREATE TABLE ContasPagar
(
	Id INT IDENTITY(1,1) NOT NULL,
	DataRegistro DATETIME NOT NULL DEFAULT(GETDATE()),
	DataVencimento DATETIME NOT NULL,
	Valor MONEY NOT NULL,
	Historico VARCHAR(1000) NOT NULL,
	CodigoBarrasDigitavel VARCHAR(100) SPARSE NULL,
	Liquidado BIT NOT NULL DEFAULT(0),
	CONSTRAINT PK_CONTASPAGAR PRIMARY KEY NONCLUSTERED(Id)

)
