CREATE TABLE ContasLiquidadas
(
	Id INT IDENTITY(1,1) NOT NULL,
	ContaPagarId INT NOT NULL,
	OrigemPagamentoId INT NOT NULL,
	DataRegistro DATETIME NOT NULL DEFAULT(GETDATE()),
	DataPagamento DATETIME NOT NULL,
	Valor MONEY NOT NULL,
	ValorPago MONEY NOT NULL,
	Historico VARCHAR(1000) NOT NULL,
	Estornado BIT NOT NULL DEFAULT(0),
	Integracao BIT NOT NULL DEFAULT(0),
	CONSTRAINT PK_CONTASLIQUIDADAS PRIMARY KEY NONCLUSTERED(Id),
	CONSTRAINT FK_CONTASLIQUIDADAS_CONTAPAGAR FOREIGN KEY (ContaPagarId) REFERENCES ContasPagar(Id),
	CONSTRAINT FK_CONTASLIQUIDADAS_ORIGEMPAGAMENTO FOREIGN KEY (OrigemPagamentoId) REFERENCES OrigensPagamentos(Id)
)
