CREATE TABLE Permissoes
(
	Id INT IDENTITY NOT NULL,
	Nome	VARCHAR(100) NOT NULL,
	Descricao	VARCHAR(300) NOT NULL,
	GrupoId		INT NOT NULL,
	ModuloId	INT NOT NULL,
	CONSTRAINT PK_PERMISSOES PRIMARY KEY NONCLUSTERED (Id),
	CONSTRAINT FK_PERMISSOES_GRUPOS FOREIGN KEY (GrupoId) REFERENCES Grupo(Id),
	CONSTRAINT FK_PERMISSOES_MODULOS FOREIGN KEY (ModuloId) REFERENCES Modulos(Id)
)
