CREATE TABLE Caixa
(
	Id INT IDENTITY(1,1) NOT NULL,
	DataAbertura DATETIME NOT NULL DEFAULT(GETDATE()),
	DataFechamento DATETIME SPARSE NULL,
	SaldoAnterior MONEY NOT NULL,
	SaldoFinal		MONEY NOT NULL,
	CONSTRAINT PK_CAIXA PRIMARY KEY NONCLUSTERED(Id)
)
