CREATE TABLE A001_AlegacaoPagador
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo VARCHAR(4) NOT NULL,
	Significado VARCHAR(100) NOT NULL,
	CONSTRAINT PK_ALEGACAOPAGADOR PRIMARY KEY NONCLUSTERED (Id),
	CONSTRAINT UK_ELGACAOPAGADOR_CODIGO UNIQUE (Codigo)
)
