CREATE TABLE C006_CodigoCarteira
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo INT NOT NULL,
	Descricao VARCHAR(50),
	CONSTRAINT PK_CODIGOCARTEIRA PRIMARY KEY NONCLUSTERED (Id),
	CONSTRAINT UK_CODIGOCARTEIRA_CODIGO UNIQUE (Codigo)
)
