CREATE TABLE C008_TipoDocumento
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo INT NOT NULL,
	Descricao VARCHAR(50) NOT NULL,
	CONSTRAINT PK_TIPODOCUMENTO PRIMARY KEY NONCLUSTERED (Id),
	CONSTRAINT UK_TIPODOCUMENTO_CODIGO UNIQUE (Codigo)
)
