CREATE TABLE C009_IdentEmissaoBoletoPagamento
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo INT NOT NULL,
	Descricao VARCHAR(50) NOT NULL,
	CONSTRAINT PK_IDENTIFICACAOEMISSAOBOLETOPAGAMENTO PRIMARY KEY NONCLUSTERED (Id)
)
