CREATE TABLE C010_IdentDistribuicao
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo VARCHAR(2) NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	CONSTRAINT PK_IDENTIFICACAODADISTRIBUICAO PRIMARY KEY NONCLUSTERED (Id),
)
