CREATE TABLE C016_IdentTituloAceito
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo CHAR(1) NOT NULL,
	Descricao VARCHAR(10) NOT NULL
	CONSTRAINT PK_IDENTIFICACAODETITULOACEITONAOACEITO PRIMARY KEY NONCLUSTERED (Id)
)
