CREATE TABLE C047_MotivoOcorrencia
(
	Id INT IDENTITY(1,1) NOT NULL,
	TipoId INT NOT NULL,
	Codigo VARCHAR(2) NOT NULL,
	Descricao VARCHAR(200) NOT NULL,
	LiquidacaoBaixa Char(1) SPARSE NULL,
	CONSTRAINT PK_MOTIVOOCORRENCIA PRIMARY KEY NONCLUSTERED (Id),
	CONSTRAINT FK_MOTIVOOCORRENCIA_TIPOMOTIVOOCORRENCIA FOREIGN KEY (TipoId) REFERENCES C047A_TipoMotivoOcorrencia(Id)

)
