CREATE TABLE C047A_TipoMotivoOcorrencia
(
	Id INT IDENTITY(1,1) NOT NULL,
	Tipo CHAR(1) NOT NULL,
	Descricao VARCHAR(200) NOT NULL,
	CONSTRAINT PK_TIPOMOVITOOCORRENCIA PRIMARY KEY NONCLUSTERED (Id)
)
