CREATE TABLE F005_NaturezaSituacaoSaldoInicial
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo CHAR(1) NOT NULL,
	Descricao VARCHAR(50) NOT NULL,
	CONSTRAINT PK_NATUREZASIUTACAOSALDOINICIAL PRIMARY KEY NONCLUSTERED (ID)
)
