CREATE TABLE G059_CodigoOcorrenciaRetornoRemessa
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo VARCHAR(2) NOT NULL,
	Descricao VARCHAR(200) NOT NULL,
	CONSTRAINT PK_CODIGOOCORRENCIARETORNOREMESSA PRIMARY KEY NONCLUSTERED(Id)
)
