CREATE TABLE G061_CodigoInstrucaoMovimento
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo VARCHAR(2) NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	CONSTRAINT PK_CODIGOINSTRUCAOMOVIMENTO PRIMARY KEY NONCLUSTERED (Id)
)
