CREATE TABLE G062_CodigoPadraoOcorrenciasPagador
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo VARCHAR(2) NOT NULL,
	Descricao VARCHAR(50) NOT NULL,
	CONSTRAINT PK_CODIGOPADRAOOCORRENCIASPAGADOR PRIMARY KEY NONCLUSTERED (Id)
)
