CREATE TABLE G085_TipoComplementoLancamento
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo VARCHAR(2) NOT NULL,
	Descricao VARCHAR(50) NOT NULL,
	CONSTRAINT PK_TIPOCOMPLEMENTOLANCAMENTO PRIMARY KEY NONCLUSTERED(Id)
)
