CREATE TABLE H010_SituacaoSindicalMutuario
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo INT NOT NULL,
	Descricao VARCHAR(50) NOT NULL,
	CONSTRAINT PK_SITUACAOSINDICALMUTUARIO PRIMARY KEY NONCLUSTERED(Id)
)
