CREATE TABLE H011_ComprometimentoVerbaRescisoria
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo INT NOT NULL,
	Descricao VARCHAR(3),
	CONSTRAINT PK_COMPROMETIMENTOVERBARECISORIA PRIMARY KEY NONCLUSTERED (Id)
)
