CREATE TABLE I004_RegimeEncargosFinanceiros
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo INT NOT NULL,
	Descricao VARCHAR(50) NOT NULL,
	CONSTRAINT PK_REGIMEENCARGOSFINANCEIROS PRIMARY KEY NONCLUSTERED (Id)
)
