CREATE TABLE I005_ModalidadeEncargosFinanceirosPos
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo VARCHAR(2) NOT NULL,
	Descricao VARCHAR(30) NOT NULL,
	CONSTRAINT PK_MODALIDADEENCARGOSFINANCEIROSPOS PRIMARY KEY NONCLUSTERED(Id)
)
