CREATE TABLE I008_MetodologiaCalculoEncargos
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo INT NOT NULL,
	Descricao VARCHAR(30) NOT NULL,
	CONSTRAINT PK_METODOLOGIACALCULOENCARGOS PRIMARY KEY NONCLUSTERED(Id)
)
