CREATE TABLE I011_TipoVencimentoParcelas
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo INT NOT NULL,
	Descricao VARCHAR(50) NOT NULL,
	Detalhe VARCHAR(200) NOT NULL,
	CONSTRAINT PK_TIPOVENCIMENTOPARCELAS PRIMARY KEY NONCLUSTERED(Id)
)
