CREATE TABLE K004_FormaEntradaDadosCheque
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo INT NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	Complemento VARCHAR(100) NOT NULL,
	CONSTRAINT PK_FORMAENTRADADADOSCHEQUE PRIMARY KEY NONCLUSTERED(Id)
)
