CREATE TABLE K020_CodigoOcorrencia
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo VARCHAR(2) NOT NULL,
	Descricao VARCHAR(50) NOT NULL,
	CONSTRAINT PK_CODIGOOCORRENCIACHEQUES PRIMARY KEY NONCLUSTERED (Id)
)
