CREATE TABLE N003_TipoIdentificacaoContribuinte
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo INT NOT NULL,
	Descricao VARCHAR(50) NOT NULL,
	CONSTRAINT PK_TIPOIDENTIFICACAOCONTRIBUINTE PRIMARY KEY NONCLUSTERED (Id)
)
