CREATE TABLE N005_CodigoIdentificacaoTributo
(
	Id INT IDENTITY(1,1) NOT NULL,
	TipoId INT NOT NULL,
	Codigo VARCHAR(2) NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	CONSTRAINT PK_CODIGOIDENTIFICACAOTRIBUTO PRIMARY KEY NONCLUSTERED (Id),
	CONSTRAINT FK_CODIGOIDENTIFICACAOTRIBUTO_TIPOTRIBUTO FOREIGN KEY (TipoId) REFERENCES N005A_TipoTributo(Id)
)
