CREATE TABLE P005_ComplementoTipoServico
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo VARCHAR(2) NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	CONSTRAINT PK_COMPLEMENTOTIPOSERVICOPAGAMENTO PRIMARY KEY NONCLUSTERED (Id)
)
