CREATE TABLE V010A_TipoMotivoOcorrencia
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo CHAR(1) NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	CONSTRAINT PK_TIPOMOTIVOOCORRENCIA PRIMARY KEY NONCLUSTERED (Id)
)
