CREATE TABLE V010_MotivoOcorrencia
(
	Id INT IDENTITY(1,1) NOT NULL,
	TipoId	INT NOT NULL,
	Codigo VARCHAR(5) NOT NULL,
	Descricao VARCHAR(200) NOT NULL,
	LiquidacaoBaixa CHAR(1) SPARSE NULL,
	CONSTRAINT PK_MOTIVOOCORRENCIAVENDOR PRIMARY KEY NONCLUSTERED (Id),
	CONSTRAINT FK_MOTIVOOCORRENCIAVENDOR_TIPOMOTIVOOCORRENCIA FOREIGN KEY (TipoId) REFERENCES V010A_TipoMotivoOcorrencia(Id)
)
