CREATE TABLE V032_CodigoMoedaVendedor
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo VARCHAR(2) NOT NULL,
	Descricao VARCHAR(50)  NOT NULL,
	CONSTRAINT PK_CODIGOMOEDAVENDEDOR PRIMARY KEY NONCLUSTERED (Id)
)
