CREATE TABLE V047_TipoLancamentoValorEqualizacao
(
	Id INT IDENTITY(1,1) NOT NULL,
	Codigo CHAR(1) NOT NULL,
	Descricao VARCHAR(20) NOT NULL,
	CONSTRAINT PK_TIPOLANCAMENTOVALOREQUALIZACAO PRIMARY KEY NONCLUSTERED (Id)
)
