CREATE TABLE EnderecosClientes
(
	Id				INT IDENTITY(1,1) NOT NULL,
	Logradouro		VARCHAR(300) NOT NULL,
	Complemento		VARCHAR(800) SPARSE NULL,
	Numero			VARCHAR(10) NOT NULL,
	Cep				VARCHAR(8) NOT NULL,
	Responsavel		BIT NOT NULL DEFAULT(0),
	UfId			INT NOT NULL,
	CidadeId		INT NOT NULL,
	BairroId		INT NOT NULL,
	TipoEnderecoId	INT NOT NULL,
	ClienteId		INT NOT NULL,
	CONSTRAINT PK_ENDERECOSCLIENTES PRIMARY KEY (Id),
	CONSTRAINT FK_ENDERECOSCLIENTES_CLIENTES FOREIGN KEY (ClienteId) REFERENCES Clientes(Id),
	CONSTRAINT FK_ENDERECOSCLIENTES_UF FOREIGN KEY (UfId) REFERENCES Estados(Id),
	CONSTRAINT FK_ENDERECOSCLIENTES_CIDADE FOREIGN KEY (CidadeId) REFERENCES Cidades(Id),
	CONSTRAINT FK_ENDERECOSCLIENTES_BAIRRO FOREIGN KEY (BairroId) REFERENCES Bairros(Id)
)
