CREATE TABLE Incisos
(
	Id			INT IDENTITY(1,1) NOT NULL,
	ClausulaId	INT NOT NULL,
	Termo		NVARCHAR(500) NOT NULL,
	CONSTRAINT PK_INCISOS PRIMARY KEY NONCLUSTERED (Id),
	CONSTRAINT FK_INCISO_CLAUSULA FOREIGN KEY (ClausulaId) REFERENCES Clausulas(Id)
)
