CREATE TABLE EnderecosFabrica
(
	Id				INT IDENTITY(1,1) NOT NULL,
	Logradouro		VARCHAR(300) NOT NULL,
	Complemento		VARCHAR(1000) NOT NULL,
	Numero			VARCHAR(10) NOT NULL,
	Cep				VARCHAR(8) NOT NULL,
	UfId			INT NOT NULL,
	CidadeId		INT NOT NULL,
	BairroId		INT NOT NULL,
	TipoEnderecoId	INT NOT NULL,
	FabricaId		INT NOT NULL,
	CONSTRAINT PK_ENDERECOSFABRICA PRIMARY KEY (Id),
	CONSTRAINT FK_ENDERECOSFABRICA_ESTADOS FOREIGN KEY (UfId) REFERENCES Estados(Id),
	CONSTRAINT FK_ENDERECOSFABRICA_CIDADES FOREIGN KEY (CidadeId) REFERENCES Cidades(Id),
	CONSTRAINT FK_ENDERECOSFABRICA_TIPO	   FOREIGN KEY (TipoEnderecoId)	REFERENCES TiposEndereco(Id),
	CONSTRAINT FK_ENDERECOSFABRICA_FABRICA FOREIGN KEY (FabricaId) REFERENCES Fabrica(Id)
	
)
