CREATE TABLE Seriais
(
	Id		INT IDENTITY(1,1) NOT NULL,
	SoftwareId	INT NOT NULL,
	ClienteId	INT NOT NULL,
	ContratoId	INT NOT NULL,
	Chave		VARCHAR(40) SPARSE NULL,
	HashChave	VARCHAR(1000) SPARSE NULL,
	HashCliente VARCHAR(1000) NOT NULL,
	CONSTRAINT PK_SERIAL PRIMARY KEY NONCLUSTERED (Id),
	CONSTRAINT FK_SERIAL_SOFTWARE FOREIGN KEY (SoftwareId) REFERENCES Softwares(Id),
	CONSTRAINT FK_SERIAL_CLIENTE FOREIGN KEY (ClienteId) REFERENCES Clientes(Id),
	CONSTRAINT FK_SERIAL_CONTRATO FOREIGN KEY (ContratoId) REFERENCES Contratos(Id)
)
