CREATE TABLE Bairros
(
	Id			INT IDENTITY(1,1) NOT NULL,
	Nome		VARCHAR(300) NOT NULL,
	CidadeId	INT NOT NULL,
	CONSTRAINT PK_BAIRROS PRIMARY KEY (Id),
	CONSTRAINT FK_BAIRROS_CIDADES FOREIGN KEY (CidadeId) REFERENCES Cidades(Id)
)
