CREATE TABLE Cidades
(
	Id			INT IDENTITY(1,1) NOT NULL,
	Nome		VARCHAR(300) NOT NULL,
	CodIbge		VARCHAR(20) NOT NULL,
	EstadoId	INT NOT NULL,
	CONSTRAINT PK_CIDADES PRIMARY KEY (Id),
	CONSTRAINT FK_CIDADES_ESTADOS FOREIGN KEY (EstadoId) REFERENCES Estados(Id)
)

