CREATE TABLE Estados
(
	Id INT IDENTITY(1,1) NOT NULL,
	Nome	VARCHAR(300) NOT NULL,
	Uf		VARCHAR(2) NOT NULL,
	CodIbge	VARCHAR(2) NOT NULL,
	CONSTRAINT PK_ESTADOS PRIMARY KEY (Id),
	CONSTRAINT U_ESTADOS_UF UNIQUE (Uf),
	CONSTRAINT U_ESTADOS_IBGE UNIQUE (CodIbge)
)
