CREATE TABLE TelefonesContatosFabrica
(
	Id				INT IDENTITY(1,1) NOT NULL,
	Numero			VARCHAR(11) NOT NULL,
	Operadora		VARCHAR(20) SPARSE NULL,
	Ramal			VARCHAR(5) SPARSE NULL,
	TipoTelefoneId	INT NOT NULL,
	ContatoId		INT NOT NULL,
	CONSTRAINT PK_TELEFONESCOSNTATOSFABRICA PRIMARY KEY (Id),
	CONSTRAINT FK_TELEFONESCOSNTATOSFABRICA_TIPO FOREIGN KEY (TipoTelefoneId) REFERENCES TiposTelefone(Id),
	CONSTRAINT FK_TELEFONESCOSNTATOSFABRICA_CONTATO FOREIGN KEY (ContatoId) REFERENCES ContatosFabrica(Id)
)
